import { useEffect, useState } from 'react';
import api from '../api/client';
import LoadingSpinner from '../components/ui/LoadingSpinner';
import { Settings2, Database, Brain, Server, RefreshCw, CheckCircle2, XCircle, Table2 } from 'lucide-react';

export default function Admin() {
  const [status, setStatus] = useState<any>(null);
  const [online, setOnline] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const [dash, ai, assets, tasks, blocks, trains, corridors, resources] = await Promise.all([api.get('/dashboard/summary'), api.get('/ai/model-status'), api.get('/assets'), api.get('/maintenance'), api.get('/blocks'), api.get('/trains'), api.get('/corridors'), api.get('/resources')]); setOnline(true); setStatus({ dash: dash.data?.data || {}, ai: ai.data?.data || {}, counts: { Assets: assets.data?.data?.length || 0, 'Maintenance Tasks': tasks.data?.data?.length || 0, Blocks: blocks.data?.data?.length || 0, Trains: trains.data?.data?.length || 0, Corridors: corridors.data?.data?.length || 0, Resources: resources.data?.data?.length || 0 } }); } catch (e: any) { setOnline(false); setError(e?.message || 'Unable to read system status.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  if (loading && !status) return <div className="h-96 flex items-center justify-center"><LoadingSpinner /></div>;
  const s = status || { dash: {}, ai: {}, counts: {} }; const models = s.ai || {};
  return <div className="space-y-6 max-w-7xl mx-auto animate-in fade-in duration-500">
    <div className="bg-white dark:bg-slate-900 p-6 rounded-xl border border-slate-200 dark:border-slate-800 flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2"><Settings2 className="text-blue-600" /> System Admin</h1><p className="text-slate-500 dark:text-slate-400 mt-1">Live system diagnostics, database inventory and AI model status.</p></div><button onClick={load} className="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-slate-200 dark:border-slate-700 text-sm font-semibold text-slate-700 dark:text-slate-200"><RefreshCw className="w-4 h-4" /> Refresh status</button></div>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <section className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 p-6"><h2 className="font-bold text-lg text-slate-900 dark:text-slate-100 flex items-center gap-2 mb-5"><Server className="w-5 h-5 text-blue-600" /> Runtime Status</h2><div className="space-y-3">{[['FastAPI Backend', online ? 'ONLINE' : 'OFFLINE'],['SQLite Database', online ? 'CONNECTED' : 'UNKNOWN'],['CP-SAT Optimizer', online ? 'READY' : 'UNKNOWN'],['API Base URL', import.meta.env.VITE_API_BASE_URL || `${window.location.protocol}//${window.location.hostname}:8000`]].map(([name,value]) => <div key={name} className="flex items-center justify-between p-3 rounded-lg bg-slate-50 dark:bg-slate-800"><span className="text-sm font-medium text-slate-600 dark:text-slate-300">{name}</span><span className="text-sm font-semibold text-emerald-600 flex items-center gap-1"><CheckCircle2 className="w-4 h-4" /> {value}</span></div>)}</div></section>
      <section className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 p-6"><h2 className="font-bold text-lg text-slate-900 dark:text-slate-100 flex items-center gap-2 mb-5"><Brain className="w-5 h-5 text-purple-600" /> AI Model Status</h2><div className="space-y-3">{[['Priority Model', models.priority_model?.loaded],['Risk Model', models.risk_model?.loaded],['Impact Model', models.impact_model?.loaded]].map(([name,loaded]) => <div key={name as string} className="flex items-center justify-between p-3 rounded-lg bg-slate-50 dark:bg-slate-800"><span className="text-sm font-medium text-slate-600 dark:text-slate-300">{name as string}</span>{loaded ? <span className="text-sm font-semibold text-emerald-600 flex items-center gap-1"><CheckCircle2 className="w-4 h-4" /> LOADED</span> : <span className="text-sm font-semibold text-red-600 flex items-center gap-1"><XCircle className="w-4 h-4" /> MISSING</span>}</div>)}</div></section>
    </div>
    <section className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 p-6"><h2 className="font-bold text-lg text-slate-900 dark:text-slate-100 flex items-center gap-2 mb-5"><Table2 className="w-5 h-5 text-slate-600" /> Database Inventory</h2><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">{Object.entries(s.counts).map(([name,count]) => <div key={name} className="p-4 rounded-lg border border-slate-200 dark:border-slate-700"><Database className="w-5 h-5 text-blue-600 mb-3" /><div className="text-2xl font-bold text-slate-900 dark:text-slate-100">{count as any}</div><div className="text-xs font-semibold text-slate-500 mt-1">{name}</div></div>)}</div></section>
    <section className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 p-6"><h2 className="font-bold text-lg text-slate-900 dark:text-slate-100 mb-3">Current KPI Snapshot</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{Object.entries(s.dash.kpis || {}).slice(0,8).map(([key,value]) => <div key={key} className="p-4 bg-slate-50 dark:bg-slate-800 rounded-lg"><div className="text-xl font-bold text-slate-900 dark:text-slate-100">{String(value)}</div><div className="text-xs text-slate-500 mt-1">{key}</div></div>)}</div></section>
  </div>;
}
